// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgihwdrfhxwuvwyfervs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnaWh3ZHJmaHh3dXZ3eWZlcnZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODQ5MTIsImV4cCI6MjA3MDE2MDkxMn0.UOVK65xODE5VxUcZi8JA9JAXDpEaaOoZvaTJyFSm8PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});